Repository etclabscore/jade-service-runner, pull requests merged in 2019-08, with the labels that each got.

#99 fix: use semantic release plugin to bump openrpc.json
  .circleci/config.yml
  .releaserc
  publish.sh
Labels: bug

#100 fix(circle): add @semantic-release/exec to npm install list
  .circleci/config.yml
Labels: bug

#101 fix(circleci): ensure docs exist
  .circleci/config.yml
  package-lock.json
  package.json
Labels: bug

#105 fix(README): add resources
  README.md
Labels: enhancement

#122 fix: linux setup and start config
  src/service-runner-config.json
Labels: bug

#123 fix(startaws): remove ~/.services/
  package.json
Labels: bug

#134 Fix/cfn
  .circleci/config.yml
  .ebextensions/nodecommand.config
  .ebextensions/npm-install-dev.config
  .elasticbeanstalk/config.yml
  .node-version
  cfn/init-production.sh
  cfn/init-staging.sh
  cfn/jade-service-runner.cfn.json
  cfn/production-launch-params.json
  cfn/staging-launch-params.json
  package-lock.json
Labels: enhancement

#135 fix: missing directory prefix
  .circleci/config.yml
Labels: bug

#136 fix: install awscli
  .circleci/config.yml
Labels: enhancement

#137 fix: missing param
  cfn/init-production.sh
  cfn/init-staging.sh
Labels: bug

#139 Fix/add region
  cfn/init-production.sh
  cfn/init-staging.sh
Labels: bug

#141 fix: fixed domain name for staging
  cfn/staging-launch-params.json
Labels: bug

#142 fix: increase timeout duration
  .circleci/config.yml
Labels: bug

#143 Fix/mistakes made
  .circleci/config.yml
  cfn/init-production.sh
  cfn/init-staging.sh
Labels: bug

#148 Fix/stack lifecycle
  .circleci/config.yml
  cfn/base-launch-params.json
  cfn/eb-application.cfn.json
  cfn/init-base.sh
  cfn/jade-service-runner.cfn.json
Labels: bug, enhancement

#150 Fix/cfn fixups
  .ebextensions/enable-websockets.config
  80/jade-service-runner-manifest.json
  cfn/init-base.sh
  cfn/jade-service-runner.cfn.json
  cfn/production-launch-params.json
  package-lock.json
Labels: bug

#165 fix: healthcheck was incorrect
  cfn/jade-service-runner.cfn.json
Labels: bug

#166 fix: remove garbo deps
  package-lock.json
  package.json
Labels: bug

#167 fix: use2xl for prod
  cfn/production-launch-params.json
Labels: bug
